const express=require('express');const http=require('http');const{Server}=require('socket.io');const cors=require('cors');
const app=express();app.use(cors());const server=http.createServer(app);const io=new Server(server,{cors:{origin:'*'}});const rooms={};const RECONNECT_MS=120000;
function code(){const c='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';let x='';do{x='';for(let i=0;i<6;i++)x+=c[Math.floor(Math.random()*c.length)]}while(rooms[x]);return x}
function set(){const s=[];for(let i=0;i<=6;i++)for(let j=i;j<=6;j++)s.push([i,j]);return s.sort(()=>Math.random()-.5)}
function need(r){return r.mode==='2v2'?4:2}function same(a,b){return a&&b&&((a[0]===b[0]&&a[1]===b[1])||(a[0]===b[1]&&a[1]===b[0]))}
function edges(r){if(!r.board.length)return{left:null,right:null};return{left:r.board[0].domino[0],right:r.board[r.board.length-1].domino[1]}}
function orient(r,d,side){if(!r.board.length)return{ok:true,domino:[...d]};const{left,right}=edges(r),[a,b]=d;if(side==='left'){if(b===left)return{ok:true,domino:[a,b]};if(a===left)return{ok:true,domino:[b,a]}}if(side==='right'){if(a===right)return{ok:true,domino:[a,b]};if(b===right)return{ok:true,domino:[b,a]}}return{ok:false}}
function legal(r,d){if(!r.board.length){if(r.firstRequired&&!same(d,r.firstRequired))return[];return['start']}const s=[];if(orient(r,d,'left').ok)s.push('left');if(orient(r,d,'right').ok)s.push('right');return s}
function hasPlay(r,p){return p.hand.some(d=>legal(r,d).length>0)}
function startInfo(r){const six=r.players.find(p=>p.hand.some(d=>d[0]===6&&d[1]===6));if(r.mode==='2v2')return{starter:six,required:[6,6]};if(six)return{starter:six,required:[6,6]};let best=null;r.players.forEach(p=>p.hand.forEach(d=>{if(d[0]===d[1]&&(!best||d[0]>best.domino[0]))best={player:p,domino:d}}));if(best)return{starter:best.player,required:[...best.domino]};let high=null;r.players.forEach(p=>p.hand.forEach(d=>{const sum=d[0]+d[1];if(!high||sum>high.sum)high={player:p,domino:d,sum}}));return{starter:high.player,required:[...high.domino]}}
function pub(r){return{code:r.code,players:r.players.map(p=>({id:p.id,pid:p.pid,name:p.name,host:p.host,team:p.team,handCount:p.hand.length,connected:p.connected!==false})),started:r.started,mode:r.mode,targetScore:r.targetScore,entryScore:r.entryScore,board:r.board,turn:r.turn,neededPlayers:need(r),boneyardCount:r.boneyard?r.boneyard.length:0,firstRequired:r.firstRequired}}
function broadcast(r){io.to(r.code).emit('roomUpdated',pub(r))}function hands(r){r.players.forEach(p=>{if(p.connected!==false)io.to(p.id).emit('yourHand',p.hand)})}
function next(r,id){const i=r.players.findIndex(p=>p.id===id);return i<0?null:r.players[(i+1)%r.players.length].id}
function autoDraw(r){if(!r.started||!r.turn||!r.board.length)return;const p=r.players.find(x=>x.id===r.turn);if(!p)return;let drew=0;while(!hasPlay(r,p)&&r.boneyard.length){p.hand.push(r.boneyard.shift());drew++}if(drew)io.to(p.id).emit('autoDrew',{count:drew});if(!hasPlay(r,p)&&!r.boneyard.length)r.turn=next(r,p.id)}
function win(r,name,why){io.to(r.code).emit('gameWon',{winnerName:name,reason:why});r.started=false;r.turn=null}
function removeAfterGrace(r,p,reason){clearTimeout(p.reconnectTimer);p.reconnectTimer=setTimeout(()=>{const room=rooms[r.code];if(!room)return;const player=room.players.find(x=>x.pid===p.pid);if(!player||player.connected!==false)return;room.players=room.players.filter(x=>x.pid!==p.pid);if(room.hostPid===p.pid&&room.players[0]){room.players[0].host=true;room.hostPid=room.players[0].pid;room.hostId=room.players[0].id}if(room.started&&room.players.length>0)win(room,room.players[0].name,reason);broadcast(room)},RECONNECT_MS)}
io.on('connection',socket=>{
 socket.on('hostGame',d=>{const pid=d.pid||socket.id,roomCode=code();rooms[roomCode]={code:roomCode,hostId:socket.id,hostPid:pid,started:false,banned:[],mode:d.mode==='2v2'?'2v2':'1v1',targetScore:+d.targetScore||100,entryScore:+d.entryScore||21,players:[{id:socket.id,pid,name:d.name||'Host',host:true,hand:[],team:1,score:0,connected:true}],board:[],turn:null,lastPlayedBy:null,boneyard:[],firstRequired:null};socket.join(roomCode);socket.emit('session',{pid,code:roomCode});socket.emit('roomJoined',pub(rooms[roomCode]))});
 socket.on('rejoinGame',d=>{const r=rooms[(d.code||'').toUpperCase()];if(!r)return socket.emit('errorMessage','Room not found');const p=r.players.find(x=>x.pid===d.pid);if(!p)return socket.emit('errorMessage','Reconnect session not found');clearTimeout(p.reconnectTimer);p.id=socket.id;p.connected=true;if(r.hostPid===p.pid)r.hostId=socket.id;socket.join(r.code);socket.emit('session',{pid:p.pid,code:r.code});socket.emit('roomJoined',pub(r));socket.emit('yourHand',p.hand);broadcast(r)});
 socket.on('joinGame',d=>{const r=rooms[(d.code||'').toUpperCase()];if(!r)return socket.emit('errorMessage','Room not found');if(r.banned.includes(d.name))return socket.emit('errorMessage','You are banned from this room');if(r.started)return socket.emit('errorMessage','Game already started');if(r.players.length>=need(r))return socket.emit('errorMessage','Room is full');const pid=d.pid||socket.id,team=r.mode==='2v2'?(r.players.length%2)+1:r.players.length+1;r.players.push({id:socket.id,pid,name:d.name||'Player',host:false,hand:[],team,score:0,connected:true});socket.join(r.code);socket.emit('session',{pid,code:r.code});broadcast(r)});
 socket.on('kickPlayer',d=>{const r=rooms[d.code];if(!r||r.hostId!==socket.id||r.started)return;const p=r.players.find(x=>x.id===d.playerId);if(!p)return;io.to(p.id).emit('kicked');io.sockets.sockets.get(p.id)?.leave(d.code);r.players=r.players.filter(x=>x.id!==d.playerId);broadcast(r)});
 socket.on('banPlayer',d=>{const r=rooms[d.code];if(!r||r.hostId!==socket.id||r.started)return;const p=r.players.find(x=>x.id===d.playerId);if(!p)return;r.banned.push(p.name);io.to(p.id).emit('banned');io.sockets.sockets.get(p.id)?.leave(d.code);r.players=r.players.filter(x=>x.id!==d.playerId);broadcast(r)});
 socket.on('startGame',c=>{const r=rooms[c];if(!r||r.hostId!==socket.id)return;if(r.players.length!==need(r))return socket.emit('errorMessage',`Need ${need(r)} players to start`);const dom=set();r.board=[];r.players.forEach(p=>p.hand=dom.splice(0,7));r.boneyard=dom;const s=startInfo(r);r.started=true;r.turn=s.starter.id;r.firstRequired=s.required;io.to(c).emit('gameStarted',{room:pub(r)});hands(r)});
 socket.on('getLegalSides',d=>{const r=rooms[d.code];if(!r||r.turn!==socket.id)return;socket.emit('legalSides',{domino:d.domino,sides:legal(r,d.domino)})});
 socket.on('playDomino',d=>{const r=rooms[d.code];if(!r||r.turn!==socket.id||!r.started)return;const p=r.players.find(x=>x.id===socket.id);if(!p)return;const i=p.hand.findIndex(x=>same(x,d.domino));if(i===-1)return;const raw=p.hand[i];let side=d.side||'right';if(!r.board.length)side='start';const sides=legal(r,raw);if(!sides.includes(side))return socket.emit('errorMessage','This domino cannot be placed there');const o=side==='start'?{ok:true,domino:[...raw]}:orient(r,raw,side);if(!o.ok)return socket.emit('errorMessage','This domino cannot be placed there');p.hand.splice(i,1);const placed={domino:o.domino,by:p.id,side};if(side==='left')r.board.unshift(placed);else r.board.push(placed);r.lastPlayedBy=p.id;if(!p.hand.length)win(r,p.name,'finished all dominoes');else{r.firstRequired=null;r.turn=next(r,p.id);autoDraw(r)}io.to(d.code).emit('boardUpdated',{room:pub(r)});hands(r)});
 socket.on('quitGame',c=>{const r=rooms[c];if(!r)return;const p=r.players.find(x=>x.id===socket.id);if(!p)return;r.players=r.players.filter(x=>x.id!==socket.id);socket.leave(c);if(r.started&&r.players.length>0)win(r,r.players[0].name,`${p.name} quit`);broadcast(r)});
 socket.on('disconnect',()=>{Object.values(rooms).forEach(r=>{const p=r.players.find(x=>x.id===socket.id);if(!p)return;p.connected=false;broadcast(r);removeAfterGrace(r,p,`${p.name} disconnected`)})})
});
app.get('/',(_,res)=>res.send('Domino realtime server running'));const PORT=process.env.PORT||3000;server.listen(PORT,()=>console.log('Server running on port '+PORT));
